In [1]:
import pandas as pd
import re

In [2]:
def make_stack_list(descstring):
    #should probably vectorise this(?), yuck
    stacklist = []
    toolslist = ['SQL','Python','Excel','VBA','Power BI','Javascript','Django','React','C#','Scikit-learn','Pandas','Tableau','Azure','AWS','GCP','AI']
    for tool in toolslist:
        if " " + tool.lower()+" " in descstring.lower():
            stacklist.append(tool)
    return stacklist

In [3]:
file = pd.read_csv('jobs.csv')

In [4]:
df = file.copy(deep=True)

In [5]:
df['stacklist'] = df['desc'].apply(make_stack_list)

In [6]:
df = df.loc[~df['sal'].isna()]

In [7]:
df = df.sort_values(by='stacklist', ascending = False)

In [8]:
df['link'] = "https://www.jobserve.com/gb/en/mob/job/" + df['jid']

In [9]:
dayfilt1  = df['sal'].str.lower().str.contains('day|daily| pd|p/d')
dayfilt2  = df['sal'].str.lower().str.contains("\d{2,3}pd",regex=True) & ~dayfilt1

dayfilt= dayfilt1 | dayfilt2


hourfilt  = df['sal'].str.lower().str.contains('hour| hr ')

yearfilt1  = df['sal'].str.lower().str.contains('annum|annual|year| yr | pa | p.a | p/a |salary')
yearfilt2  = df['sal'].str.lower().str.contains("\d{2,3}[kK]",regex=True) & ~yearfilt1

yearfilt = yearfilt1 | yearfilt2

df['sal'] = df['sal'].str.replace(',','')
df['sal'] = df['sal'].str.replace("\.00",'',regex=False)

df.loc[yearfilt, 'rate_type'] = "Yearly"
df.loc[dayfilt, 'rate_type'] = "Daily"
df.loc[hourfilt, 'rate_type'] = "Hourly"

In [13]:
df['digits'] = df['sal'].apply(lambda x: max(int(i) for i in re.findall('\d+', x)))
df['digits'] = df['digits'].astype(int)

In [14]:
df.loc[(yearfilt)&(df['digits']<1000),'digits'] = df['digits']*1000

In [15]:
mycols = ['jid','title','digits','rate_type']

df[df['rate_type'].isna()]

,jid,title,sal,desc,stacklist,link,rate_type,digits
713,78544A603EC03559A8,ColdFusion Developer - MFA,Quotes (inside IR35),ColdFusion Developer - MFA Our client is looki...,"[SQL, React, Azure]",https://www.jobserve.com/gb/en/mob/job/78544A6...,NaN,35
563,B5C918EA3B87F5004D,React Developer,£670 inside,React Developer - Contract Role Investment Ban...,[React],https://www.jobserve.com/gb/en/mob/job/B5C918E...,NaN,670
152,24084B45AE09FDF145,Solution Architect Retail - OMS- 6 months Exte...,£600 Inside IR-35,Solution Architect Retail - OMS Watford/Hybrid...,[React],https://www.jobserve.com/gb/en/mob/job/24084B4...,NaN,600
1259,767FD6C3C007CD37E4,Software Developer - DevOps - Contract,Up to £700/pd,I am currently working with a leading Global E...,[React],https://www.jobserve.com/gb/en/mob/job/767FD6C...,NaN,700
121,6C3125B08EECF3466A,Senior DevOps Engineer/SRE/Site Reliability En...,600 (Inside IR35) - Umbrella,We are Hiring for Senior DevOps Engineer/SRE/S...,"[Python, AWS]",https://www.jobserve.com/gb/en/mob/job/6C3125B...,NaN,600
18,86628ECC00E91C662D,Python Developer//£550 Inside IR35//London,£550 Inside IR35,One of Xpertise Recruitment's key clients is u...,[Python],https://www.jobserve.com/gb/en/mob/job/86628EC...,NaN,550
315,7A98B9C5A0D9985C7D,Tableau Visualisation Expert,up to £90000 + Bonus + Benefits,An active investment management firm focused o...,"[Excel, Tableau]",https://www.jobserve.com/gb/en/mob/job/7A98B9C...,NaN,90000
314,E7B7CEF869A2DB05D8,Data Analyst,up to £90000 + Bonus + Benefits,An active investment management firm focused o...,"[Excel, Tableau]",https://www.jobserve.com/gb/en/mob/job/E7B7CEF...,NaN,90000
1221,B28BF92020616E3FF7,C# Developer,£500 Outside IR35,I am currently representing a client who are s...,[C#],https://www.jobserve.com/gb/en/mob/job/B28BF92...,NaN,500
919,99706B127BCC6B9085,Engineering Lead - Infrastructure Provisioning...,£70784 - £132720,End DateThursday 08 December 2022Salary Range£...,"[Azure, GCP]",https://www.jobserve.com/gb/en/mob/job/99706B1...,NaN,132720
220,B82262220EFD2C3378,Engineering Lead - Cloud Developer User Experi...,£70784 - £132720,End DateThursday 08 December 2022Salary Range£...,"[Azure, GCP]",https://www.jobserve.com/gb/en/mob/job/B822622...,NaN,132720
480,DD1D9A1C0B3F67215D,Azure Devops - Investment Banking - Inside up ...,up to £700 inside,I am working with a large Investment bank in L...,[Azure],https://www.jobserve.com/gb/en/mob/job/DD1D9A1...,NaN,700
1119,5B85630B312D066C9D,Atlassian Architect - London/WFH/Mainly Remote,£500 - £550 (Outside IR35),Atlassian Architect - London/WFH/Mainly Remote...,[AWS],https://www.jobserve.com/gb/en/mob/job/5B85630...,NaN,550
1260,1DB1DF115FAD381D6B,Software Engineer (Backend) - Contract,Up to £700/pd,I am currently working with a leading Global E...,[AWS],https://www.jobserve.com/gb/en/mob/job/1DB1DF1...,NaN,700
1261,6330E40F7D6A47537C,Full stack Software Developer - Contract,Up to £700/pd,I am currently working with a leading Global E...,[AWS],https://www.jobserve.com/gb/en/mob/job/6330E40...,NaN,700
504,476F6DB70D331427F7,Cloud Native API Solution Architect (commercet...,excellent rates (outside IR35) or salaries,Cloud Native API Microservices Solution Archit...,[AWS],https://www.jobserve.com/gb/en/mob/job/476F6DB...,NaN,35
939,8AAB79A87841747D79,Principal Incident & Problem Specialist,Inside IR35,KEY RESPONSIBILITIES & ACCOUNTABILITIES To o...,[],https://www.jobserve.com/gb/en/mob/job/8AAB79A...,NaN,35
1345,CCC77778B6A538AF5A,Enterprise Architect - Local Government Experi...,Inside IR35,The role will be leading the architecture and ...,[],https://www.jobserve.com/gb/en/mob/job/CCC7777...,NaN,35
913,14A9BC753AC1181A7E,Data Engineering Lead,£60500-£70877 Civil Service Benefit,Excellent opportunity to join the Civil Servic...,[],https://www.jobserve.com/gb/en/mob/job/14A9BC7...,NaN,70877
910,97E6EC611194C85E0B,Senior NOC Engineer,£48500 - £60000,"Senior NOC Engineer Hemel Hempstead £48,500 -...",[],https://www.jobserve.com/gb/en/mob/job/97E6EC6...,NaN,60000
1301,6D955A743B17F9CEC2,Product Marketing Manager,£400 inside IR35,The Role: This role will be responsible for th...,[],https://www.jobserve.com/gb/en/mob/job/6D955A7...,NaN,400
1164,81CEDBE8C3423E5D98,Change and Transformation Business Analyst,£52613 - £62178,Are you a self-reliant Business Analyst seekin...,[],https://www.jobserve.com/gb/en/mob/job/81CEDBE...,NaN,62178
1228,19A604139FD8D79137,Project Coordinator,Inside IR35,Title: Project Coordinator Duration: 6 months ...,[],https://www.jobserve.com/gb/en/mob/job/19A6041...,NaN,35
682,011DFF91D309657E7E,D365 R2R Product Owner,Circa £100000,New Opportunity - D365 R2R Product Owner - Hyb...,[],https://www.jobserve.com/gb/en/mob/job/011DFF9...,NaN,100000
306,A7378EF829229B3C04,Security Business Analyst,650 Inside IR35,Security Business Analyst Immediate Requiremen...,[],https://www.jobserve.com/gb/en/mob/job/A7378EF...,NaN,650
218,21E9001E27A48E9F77,Software Engineer - Microsoft Dynamics CRM,£61176 - £99411,End DateFriday 02 December 2022Salary Range£61...,[],https://www.jobserve.com/gb/en/mob/job/21E9001...,NaN,99411
219,CC556E73A2F2102E68,"Solutions Architect, Software Engineering (Fin...",£57861 - £98423,End DateWednesday 30 November 2022Salary Range...,[],https://www.jobserve.com/gb/en/mob/job/CC556E7...,NaN,98423
312,0E79A192A4F8104E47,".NET Developer - IT Services (up to 65,000 GBP)",up to 65000 GBP,Our client looking for a ..NET Web Developer -...,[],https://www.jobserve.com/gb/en/mob/job/0E79A19...,NaN,65000
405,D58B226ED3AA3F8654,ETRM Project Manager - Align ETRM Experience R...,TBC (outside IR35),ETRM Project Manager Opportunity - Align ETRM ...,[],https://www.jobserve.com/gb/en/mob/job/D58B226...,NaN,35
406,8CD3129D72ACD7B993,ETRM Business Analyst (Align) - Outside IR35,TBC (outside IR35),ETRM Business Analyst Opportunity - Align ETRM...,[],https://www.jobserve.com/gb/en/mob/job/8CD3129...,NaN,35
374,C3E041B6898768087E,Regional Engagement Lead,Inside IR35,My banking client has a vacancy for a Regional...,[],https://www.jobserve.com/gb/en/mob/job/C3E041B...,NaN,35
202,B655AA19D09E09F0B3,Data Entry Clerk Work From Home - Part-Time Fo...,£700/Week,Job Title: Data Entry Clerk Work From Home - R...,[],https://www.jobserve.com/gb/en/mob/job/B655AA1...,NaN,700
75,E19C66E7C7056CD7BE,Technical Business Analyst,InsideIR35 - TBD,My banking client is seeking to hire a Technic...,[],https://www.jobserve.com/gb/en/mob/job/E19C66E...,NaN,35
5,E090FDEFEACDEBA140,1st Line Support Engineers (Graduate),£150-£175,1st Line Support Engineers (x4) Initial 3-mont...,[],https://www.jobserve.com/gb/en/mob/job/E090FDE...,NaN,175
7,BA8FFD10F00E0BC24A,Lead Data Engineer,£450 - 500,Lead Data Engineer -Banking Domain -12 month c...,[],https://www.jobserve.com/gb/en/mob/job/BA8FFD1...,NaN,500
117,7BA5DB93F1068DE183,Regional Engagement/Delivery Lead,£650 inside IR35,One of our global banking client is looking fo...,[],https://www.jobserve.com/gb/en/mob/job/7BA5DB9...,NaN,650
690,5759B86409633EAEFB,Lead Software Engineer,£81928 - £153615,End DateSunday 04 December 2022Salary Range£81...,[],https://www.jobserve.com/gb/en/mob/job/5759B86...,NaN,153615
847,9BBEA13C6182A24CEC,"Java Developer; Java, Spring, Springboot, Rest...",Outside IR35 Negotiable,"Java Developer; Java, Spring, Springboot, Rest...",[],https://www.jobserve.com/gb/en/mob/job/9BBEA13...,NaN,35
762,26B8763A100031FD8D,.NET Web Developer - Technology & Telecoms (up...,up to 65000 GBP,Our client looking for a Software Developer to...,[],https://www.jobserve.com/gb/en/mob/job/26B8763...,NaN,65000
434,B2AA8B91D8441ADD4F,Pega Developer,up to £110000 p/a,"Do you have business architecture experience, ...",[],https://www.jobserve.com/gb/en/mob/job/B2AA8B9...,NaN,110000
557,6698D5BD0CA27C7BF7,Business Analyst,Negotiable (Inside IR35),Looking for experienced Business Analysts for ...,[],https://www.jobserve.com/gb/en/mob/job/6698D5B...,NaN,35